---
resources:
  - ../base
namespace: deployment-metro-rbd
commonLabels:
  app: deployment-metro-rbd
patches:
  # Customize path to application.
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/deployment/odr-metro-rbd
        
